import type { Product, Brand, Category } from '@/types';

// Mock Brands
export const mockBrands: Brand[] = [
    {
        id: '1',
        name: 'TechPro',
        slug: 'techpro',
        description: 'Premium technology products',
    },
    {
        id: '2',
        name: 'StyleHub',
        slug: 'stylehub',
        description: 'Fashion and lifestyle',
    },
    {
        id: '3',
        name: 'HomeComfort',
        slug: 'homecomfort',
        description: 'Quality home products',
    },
    {
        id: '4',
        name: 'SportMax',
        slug: 'sportmax',
        description: 'Sports and fitness equipment',
    },
    {
        id: '5',
        name: 'BeautyGlow',
        slug: 'beautyglow',
        description: 'Beauty and cosmetics',
    },
];

// Mock Categories
export const mockCategories: Category[] = [
    {
        id: '1',
        name: 'Electronics',
        slug: 'electronics',
        description: 'Latest electronic devices',
        productCount: 156,
    },
    {
        id: '2',
        name: 'Fashion',
        slug: 'fashion',
        description: 'Clothing and accessories',
        productCount: 324,
    },
    {
        id: '3',
        name: 'Home & Living',
        slug: 'home-living',
        description: 'Home decoration and furniture',
        productCount: 89,
    },
    {
        id: '4',
        name: 'Sports',
        slug: 'sports',
        description: 'Sports and fitness',
        productCount: 142,
    },
    {
        id: '5',
        name: 'Beauty',
        slug: 'beauty',
        description: 'Beauty and cosmetics',
        productCount: 98,
    },
];

// Mock Products
export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Wireless Noise Cancelling Headphones',
        slug: 'wireless-noise-cancelling-headphones',
        description:
            'Premium wireless headphones with active noise cancellation technology. Experience crystal-clear sound quality with deep bass and 30-hour battery life.',
        shortDescription: 'Premium wireless headphones with ANC',
        images: [
            {
                id: 'img1',
                url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
                alt: 'Wireless Headphones Front View',
                width: 800,
                height: 800,
            },
            {
                id: 'img2',
                url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
                alt: 'Wireless Headphones Side View',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 2499,
            currency: 'TRY',
            formatted: '₺2,499.00',
        },
        originalPrice: {
            amount: 3499,
            currency: 'TRY',
            formatted: '₺3,499.00',
        },
        discount: {
            type: 'percentage',
            value: 28,
            label: '28% OFF',
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.5,
            count: 128,
            distribution: {
                5: 78,
                4: 32,
                3: 12,
                2: 4,
                1: 2,
            },
        },
        stock: {
            available: 45,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Battery Life', value: '30 hours' },
            { name: 'Bluetooth Version', value: '5.2' },
            { name: 'Weight', value: '250g' },
        ],
        tags: ['wireless', 'audio', 'noise-cancelling'],
        createdAt: '2024-12-01T10:00:00Z',
        updatedAt: '2024-12-20T15:30:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '2',
        name: 'Smart Watch Pro Series 7',
        slug: 'smart-watch-pro-series-7',
        description:
            'Advanced smartwatch with health tracking, GPS, and water resistance. Monitor your fitness goals with precision and style.',
        shortDescription: 'Advanced fitness and health tracking smartwatch',
        images: [
            {
                id: 'img3',
                url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
                alt: 'Smart Watch Display',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 4299,
            currency: 'TRY',
            formatted: '₺4,299.00',
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.7,
            count: 256,
            distribution: {
                5: 189,
                4: 45,
                3: 15,
                2: 5,
                1: 2,
            },
        },
        stock: {
            available: 23,
            status: 'in-stock',
        },
        variants: [
            {
                id: 'v1',
                name: 'Color',
                type: 'color',
                value: 'Black',
                stock: 12,
            },
            {
                id: 'v2',
                name: 'Color',
                type: 'color',
                value: 'Silver',
                stock: 11,
            },
        ],
        attributes: [
            { name: 'Display', value: '1.9" AMOLED' },
            { name: 'Water Resistance', value: '5 ATM' },
            { name: 'Battery Life', value: '7 days' },
        ],
        tags: ['smartwatch', 'fitness', 'health'],
        createdAt: '2024-11-15T08:00:00Z',
        updatedAt: '2024-12-18T12:00:00Z',
        isFeatured: true,
        isNew: true,
    },
    {
        id: '3',
        name: 'Premium Leather Jacket',
        slug: 'premium-leather-jacket',
        description:
            'Genuine leather jacket with modern design. Perfect for all seasons with comfortable fit and timeless style.',
        shortDescription: 'Genuine leather jacket with modern fit',
        images: [
            {
                id: 'img4',
                url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
                alt: 'Leather Jacket',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 1899,
            currency: 'TRY',
            formatted: '₺1,899.00',
        },
        originalPrice: {
            amount: 2499,
            currency: 'TRY',
            formatted: '₺2,499.00',
        },
        discount: {
            type: 'percentage',
            value: 24,
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.3,
            count: 89,
            distribution: {
                5: 45,
                4: 28,
                3: 12,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 8,
            status: 'low-stock',
        },
        variants: [
            {
                id: 'v3',
                name: 'Size',
                type: 'size',
                value: 'S',
                stock: 2,
            },
            {
                id: 'v4',
                name: 'Size',
                type: 'size',
                value: 'M',
                stock: 3,
            },
            {
                id: 'v5',
                name: 'Size',
                type: 'size',
                value: 'L',
                stock: 3,
            },
        ],
        attributes: [
            { name: 'Material', value: '100% Genuine Leather' },
            { name: 'Lining', value: 'Polyester' },
            { name: 'Care', value: 'Dry Clean Only' },
        ],
        tags: ['fashion', 'leather', 'jacket'],
        createdAt: '2024-10-20T14:00:00Z',
        updatedAt: '2024-12-15T09:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '4',
        name: 'Modern Coffee Table Set',
        slug: 'modern-coffee-table-set',
        description:
            'Elegant coffee table set with tempered glass top and solid wood frame. Perfect centerpiece for your living room.',
        shortDescription: 'Glass top coffee table with wood frame',
        images: [
            {
                id: 'img5',
                url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                alt: 'Coffee Table',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 3799,
            currency: 'TRY',
            formatted: '₺3,799.00',
        },
        brand: mockBrands[2],
        category: mockCategories[2],
        rating: {
            average: 4.6,
            count: 67,
            distribution: {
                5: 42,
                4: 18,
                3: 5,
                2: 1,
                1: 1,
            },
        },
        stock: {
            available: 12,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Dimensions', value: '120 x 60 x 45 cm' },
            { name: 'Material', value: 'Oak Wood & Glass' },
            { name: 'Weight Capacity', value: '50 kg' },
        ],
        tags: ['furniture', 'living-room', 'table'],
        createdAt: '2024-09-10T11:00:00Z',
        updatedAt: '2024-12-10T16:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    // Yeni ürünler ekleniyor
    {
        id: '5',
        name: 'Wireless Bluetooth Speaker',
        slug: 'wireless-bluetooth-speaker',
        description:
            'Portable wireless speaker with 360-degree sound and 20-hour battery life. Perfect for outdoor adventures and parties.',
        shortDescription: 'Portable wireless speaker with 360° sound',
        images: [
            {
                id: 'img6',
                url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',
                alt: 'Bluetooth Speaker',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 899,
            currency: 'TRY',
            formatted: '₺899.00',
        },
        originalPrice: {
            amount: 1299,
            currency: 'TRY',
            formatted: '₺1,299.00',
        },
        discount: {
            type: 'percentage',
            value: 31,
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.4,
            count: 203,
            distribution: {
                5: 120,
                4: 55,
                3: 20,
                2: 5,
                1: 3,
            },
        },
        stock: {
            available: 34,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Battery Life', value: '20 hours' },
            { name: 'Water Resistance', value: 'IPX7' },
            { name: 'Weight', value: '680g' },
        ],
        tags: ['speaker', 'wireless', 'portable'],
        createdAt: '2024-11-20T09:00:00Z',
        updatedAt: '2024-12-19T14:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '6',
        name: 'Classic Denim Jeans',
        slug: 'classic-denim-jeans',
        description:
            'Classic fit denim jeans made from premium cotton. Comfortable, durable, and stylish for everyday wear.',
        shortDescription: 'Classic fit premium denim jeans',
        images: [
            {
                id: 'img7',
                url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
                alt: 'Denim Jeans',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 599,
            currency: 'TRY',
            formatted: '₺599.00',
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.2,
            count: 156,
            distribution: {
                5: 78,
                4: 45,
                3: 25,
                2: 5,
                1: 3,
            },
        },
        stock: {
            available: 67,
            status: 'in-stock',
        },
        variants: [
            {
                id: 'v6',
                name: 'Size',
                type: 'size',
                value: '28',
                stock: 12,
            },
            {
                id: 'v7',
                name: 'Size',
                type: 'size',
                value: '30',
                stock: 18,
            },
            {
                id: 'v8',
                name: 'Size',
                type: 'size',
                value: '32',
                stock: 20,
            },
            {
                id: 'v9',
                name: 'Size',
                type: 'size',
                value: '34',
                stock: 17,
            },
        ],
        attributes: [
            { name: 'Material', value: '98% Cotton, 2% Elastane' },
            { name: 'Fit', value: 'Classic' },
            { name: 'Wash', value: 'Stone Wash' },
        ],
        tags: ['denim', 'jeans', 'casual'],
        createdAt: '2024-10-15T10:00:00Z',
        updatedAt: '2024-12-12T11:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '7',
        name: 'Ergonomic Office Chair',
        slug: 'ergonomic-office-chair',
        description:
            'Comfortable ergonomic office chair with lumbar support and adjustable height. Perfect for long work sessions.',
        shortDescription: 'Ergonomic office chair with lumbar support',
        images: [
            {
                id: 'img8',
                url: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800',
                alt: 'Office Chair',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 2499,
            currency: 'TRY',
            formatted: '₺2,499.00',
        },
        originalPrice: {
            amount: 3299,
            currency: 'TRY',
            formatted: '₺3,299.00',
        },
        discount: {
            type: 'percentage',
            value: 24,
        },
        brand: mockBrands[2],
        category: mockCategories[2],
        rating: {
            average: 4.8,
            count: 312,
            distribution: {
                5: 245,
                4: 48,
                3: 15,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 19,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Material', value: 'Mesh & PU Leather' },
            { name: 'Weight Capacity', value: '150 kg' },
            { name: 'Adjustable Height', value: 'Yes' },
        ],
        tags: ['furniture', 'office', 'ergonomic'],
        createdAt: '2024-11-05T08:00:00Z',
        updatedAt: '2024-12-17T13:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '8',
        name: 'Running Shoes Pro',
        slug: 'running-shoes-pro',
        description:
            'Professional running shoes with advanced cushioning and breathable mesh upper. Designed for maximum comfort and performance.',
        shortDescription: 'Professional running shoes with advanced cushioning',
        images: [
            {
                id: 'img9',
                url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
                alt: 'Running Shoes',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 1299,
            currency: 'TRY',
            formatted: '₺1,299.00',
        },
        brand: mockBrands[3],
        category: mockCategories[3],
        rating: {
            average: 4.6,
            count: 189,
            distribution: {
                5: 125,
                4: 42,
                3: 18,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 42,
            status: 'in-stock',
        },
        variants: [
            {
                id: 'v10',
                name: 'Size',
                type: 'size',
                value: '40',
                stock: 8,
            },
            {
                id: 'v11',
                name: 'Size',
                type: 'size',
                value: '42',
                stock: 12,
            },
            {
                id: 'v12',
                name: 'Size',
                type: 'size',
                value: '44',
                stock: 15,
            },
            {
                id: 'v13',
                name: 'Size',
                type: 'size',
                value: '46',
                stock: 7,
            },
        ],
        attributes: [
            { name: 'Material', value: 'Mesh & Synthetic' },
            { name: 'Cushioning', value: 'Advanced Air Cushion' },
            { name: 'Weight', value: '280g' },
        ],
        tags: ['running', 'sports', 'shoes'],
        createdAt: '2024-11-10T12:00:00Z',
        updatedAt: '2024-12-16T10:00:00Z',
        isFeatured: true,
        isNew: true,
    },
    {
        id: '9',
        name: 'Vitamin C Serum',
        slug: 'vitamin-c-serum',
        description:
            'Brightening vitamin C serum with hyaluronic acid. Reduces dark spots and improves skin texture for a radiant glow.',
        shortDescription: 'Brightening vitamin C serum',
        images: [
            {
                id: 'img10',
                url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800',
                alt: 'Vitamin C Serum',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 299,
            currency: 'TRY',
            formatted: '₺299.00',
        },
        originalPrice: {
            amount: 399,
            currency: 'TRY',
            formatted: '₺399.00',
        },
        discount: {
            type: 'percentage',
            value: 25,
        },
        brand: mockBrands[4],
        category: mockCategories[4],
        rating: {
            average: 4.5,
            count: 234,
            distribution: {
                5: 145,
                4: 62,
                3: 20,
                2: 5,
                1: 2,
            },
        },
        stock: {
            available: 56,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Volume', value: '30ml' },
            { name: 'Key Ingredients', value: 'Vitamin C, Hyaluronic Acid' },
            { name: 'Skin Type', value: 'All Types' },
        ],
        tags: ['skincare', 'serum', 'vitamin-c'],
        createdAt: '2024-11-25T09:00:00Z',
        updatedAt: '2024-12-18T15:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '10',
        name: 'Gaming Mechanical Keyboard',
        slug: 'gaming-mechanical-keyboard',
        description:
            'RGB backlit mechanical keyboard with Cherry MX switches. Perfect for gaming and typing with customizable lighting effects.',
        shortDescription: 'RGB mechanical keyboard with Cherry MX switches',
        images: [
            {
                id: 'img11',
                url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
                alt: 'Mechanical Keyboard',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 1899,
            currency: 'TRY',
            formatted: '₺1,899.00',
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.7,
            count: 278,
            distribution: {
                5: 198,
                4: 58,
                3: 18,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 28,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Switch Type', value: 'Cherry MX Red' },
            { name: 'Backlight', value: 'RGB' },
            { name: 'Layout', value: 'Full Size' },
        ],
        tags: ['keyboard', 'gaming', 'mechanical'],
        createdAt: '2024-10-28T11:00:00Z',
        updatedAt: '2024-12-14T09:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '11',
        name: 'Designer Sunglasses',
        slug: 'designer-sunglasses',
        description:
            'Stylish designer sunglasses with UV400 protection and polarized lenses. Perfect for sunny days and outdoor activities.',
        shortDescription: 'Designer sunglasses with UV400 protection',
        images: [
            {
                id: 'img12',
                url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800',
                alt: 'Sunglasses',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 799,
            currency: 'TRY',
            formatted: '₺799.00',
        },
        originalPrice: {
            amount: 1199,
            currency: 'TRY',
            formatted: '₺1,199.00',
        },
        discount: {
            type: 'percentage',
            value: 33,
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.4,
            count: 167,
            distribution: {
                5: 98,
                4: 45,
                3: 18,
                2: 4,
                1: 2,
            },
        },
        stock: {
            available: 31,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Lens Type', value: 'Polarized' },
            { name: 'UV Protection', value: 'UV400' },
            { name: 'Frame Material', value: 'Acetate' },
        ],
        tags: ['sunglasses', 'accessories', 'fashion'],
        createdAt: '2024-11-12T10:00:00Z',
        updatedAt: '2024-12-13T14:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '12',
        name: 'Yoga Mat Premium',
        slug: 'yoga-mat-premium',
        description:
            'Non-slip premium yoga mat with extra thickness for comfort. Perfect for yoga, pilates, and fitness exercises.',
        shortDescription: 'Non-slip premium yoga mat',
        images: [
            {
                id: 'img13',
                url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800',
                alt: 'Yoga Mat',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 449,
            currency: 'TRY',
            formatted: '₺449.00',
        },
        brand: mockBrands[3],
        category: mockCategories[3],
        rating: {
            average: 4.6,
            count: 145,
            distribution: {
                5: 98,
                4: 32,
                3: 12,
                2: 2,
                1: 1,
            },
        },
        stock: {
            available: 78,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Thickness', value: '6mm' },
            { name: 'Material', value: 'TPE' },
            { name: 'Size', value: '183 x 61 cm' },
        ],
        tags: ['yoga', 'fitness', 'mat'],
        createdAt: '2024-11-18T08:00:00Z',
        updatedAt: '2024-12-15T11:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    // Yeni ürünler - 13'ten 24'e kadar
    {
        id: '13',
        name: 'Wireless Mouse Pro',
        slug: 'wireless-mouse-pro',
        description:
            'Ergonomic wireless mouse with precision tracking and long battery life. Perfect for work and gaming.',
        shortDescription: 'Ergonomic wireless mouse',
        images: [
            {
                id: 'img14',
                url: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800',
                alt: 'Wireless Mouse',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 399,
            currency: 'TRY',
            formatted: '₺399.00',
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.5,
            count: 198,
            distribution: {
                5: 125,
                4: 48,
                3: 20,
                2: 4,
                1: 1,
            },
        },
        stock: {
            available: 52,
            status: 'in-stock',
        },
        attributes: [
            { name: 'DPI', value: 'Up to 16000' },
            { name: 'Battery Life', value: '12 months' },
            { name: 'Connection', value: '2.4GHz Wireless' },
        ],
        tags: ['mouse', 'wireless', 'gaming'],
        createdAt: '2024-11-22T10:00:00Z',
        updatedAt: '2024-12-19T16:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '14',
        name: 'Cotton T-Shirt Classic',
        slug: 'cotton-t-shirt-classic',
        description:
            'Comfortable classic fit cotton t-shirt. Soft, breathable, and perfect for everyday wear.',
        shortDescription: 'Classic fit cotton t-shirt',
        images: [
            {
                id: 'img15',
                url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
                alt: 'Cotton T-Shirt',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 199,
            currency: 'TRY',
            formatted: '₺199.00',
        },
        originalPrice: {
            amount: 299,
            currency: 'TRY',
            formatted: '₺299.00',
        },
        discount: {
            type: 'percentage',
            value: 33,
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.3,
            count: 234,
            distribution: {
                5: 145,
                4: 62,
                3: 22,
                2: 4,
                1: 1,
            },
        },
        stock: {
            available: 89,
            status: 'in-stock',
        },
        variants: [
            {
                id: 'v14',
                name: 'Size',
                type: 'size',
                value: 'S',
                stock: 25,
            },
            {
                id: 'v15',
                name: 'Size',
                type: 'size',
                value: 'M',
                stock: 30,
            },
            {
                id: 'v16',
                name: 'Size',
                type: 'size',
                value: 'L',
                stock: 22,
            },
            {
                id: 'v17',
                name: 'Size',
                type: 'size',
                value: 'XL',
                stock: 12,
            },
        ],
        attributes: [
            { name: 'Material', value: '100% Cotton' },
            { name: 'Fit', value: 'Classic' },
            { name: 'Care', value: 'Machine Wash' },
        ],
        tags: ['t-shirt', 'casual', 'cotton'],
        createdAt: '2024-10-25T09:00:00Z',
        updatedAt: '2024-12-11T13:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '15',
        name: 'Standing Desk Converter',
        slug: 'standing-desk-converter',
        description:
            'Adjustable standing desk converter to transform your regular desk. Improve posture and productivity.',
        shortDescription: 'Adjustable standing desk converter',
        images: [
            {
                id: 'img16',
                url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                alt: 'Standing Desk',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 1299,
            currency: 'TRY',
            formatted: '₺1,299.00',
        },
        brand: mockBrands[2],
        category: mockCategories[2],
        rating: {
            average: 4.7,
            count: 156,
            distribution: {
                5: 112,
                4: 32,
                3: 10,
                2: 1,
                1: 1,
            },
        },
        stock: {
            available: 24,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Weight Capacity', value: '15 kg' },
            { name: 'Height Range', value: '15-50 cm' },
            { name: 'Material', value: 'Steel & MDF' },
        ],
        tags: ['furniture', 'office', 'standing-desk'],
        createdAt: '2024-11-08T11:00:00Z',
        updatedAt: '2024-12-16T14:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '16',
        name: 'Dumbbell Set 2x10kg',
        slug: 'dumbbell-set-2x10kg',
        description:
            'Professional dumbbell set with neoprene coating. Perfect for home workouts and strength training.',
        shortDescription: 'Professional dumbbell set 2x10kg',
        images: [
            {
                id: 'img17',
                url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
                alt: 'Dumbbells',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 899,
            currency: 'TRY',
            formatted: '₺899.00',
        },
        brand: mockBrands[3],
        category: mockCategories[3],
        rating: {
            average: 4.6,
            count: 189,
            distribution: {
                5: 132,
                4: 38,
                3: 15,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 15,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Weight', value: '2x10kg (20kg total)' },
            { name: 'Material', value: 'Cast Iron with Neoprene' },
            { name: 'Grip', value: 'Ergonomic' },
        ],
        tags: ['fitness', 'weights', 'home-gym'],
        createdAt: '2024-11-14T08:00:00Z',
        updatedAt: '2024-12-17T10:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '17',
        name: 'Hyaluronic Acid Moisturizer',
        slug: 'hyaluronic-acid-moisturizer',
        description:
            'Intensive hydrating moisturizer with hyaluronic acid. Keeps skin plump and hydrated all day.',
        shortDescription: 'Hydrating moisturizer with hyaluronic acid',
        images: [
            {
                id: 'img18',
                url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800',
                alt: 'Moisturizer',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 349,
            currency: 'TRY',
            formatted: '₺349.00',
        },
        brand: mockBrands[4],
        category: mockCategories[4],
        rating: {
            average: 4.5,
            count: 267,
            distribution: {
                5: 178,
                4: 62,
                3: 22,
                2: 4,
                1: 1,
            },
        },
        stock: {
            available: 64,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Volume', value: '50ml' },
            { name: 'Key Ingredients', value: 'Hyaluronic Acid, Ceramides' },
            { name: 'Skin Type', value: 'All Types' },
        ],
        tags: ['skincare', 'moisturizer', 'hyaluronic-acid'],
        createdAt: '2024-11-28T09:00:00Z',
        updatedAt: '2024-12-20T12:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '18',
        name: '4K Ultra HD Monitor',
        slug: '4k-ultra-hd-monitor',
        description:
            '27-inch 4K UHD monitor with HDR support. Perfect for professional work and entertainment.',
        shortDescription: '27-inch 4K UHD monitor with HDR',
        images: [
            {
                id: 'img19',
                url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800',
                alt: '4K Monitor',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 5499,
            currency: 'TRY',
            formatted: '₺5,499.00',
        },
        originalPrice: {
            amount: 6999,
            currency: 'TRY',
            formatted: '₺6,999.00',
        },
        discount: {
            type: 'percentage',
            value: 21,
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.8,
            count: 312,
            distribution: {
                5: 245,
                4: 48,
                3: 15,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 18,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Screen Size', value: '27 inch' },
            { name: 'Resolution', value: '3840 x 2160 (4K)' },
            { name: 'Refresh Rate', value: '60Hz' },
        ],
        tags: ['monitor', '4k', 'display'],
        createdAt: '2024-10-30T10:00:00Z',
        updatedAt: '2024-12-18T15:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '19',
        name: 'Leather Crossbody Bag',
        slug: 'leather-crossbody-bag',
        description:
            'Stylish leather crossbody bag with adjustable strap. Perfect for daily use and travel.',
        shortDescription: 'Stylish leather crossbody bag',
        images: [
            {
                id: 'img20',
                url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
                alt: 'Crossbody Bag',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 1299,
            currency: 'TRY',
            formatted: '₺1,299.00',
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.4,
            count: 178,
            distribution: {
                5: 112,
                4: 45,
                3: 18,
                2: 2,
                1: 1,
            },
        },
        stock: {
            available: 29,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Material', value: 'Genuine Leather' },
            { name: 'Dimensions', value: '28 x 20 x 8 cm' },
            { name: 'Strap', value: 'Adjustable' },
        ],
        tags: ['bag', 'leather', 'accessories'],
        createdAt: '2024-11-16T11:00:00Z',
        updatedAt: '2024-12-14T13:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '20',
        name: 'Memory Foam Pillow',
        slug: 'memory-foam-pillow',
        description:
            'Ergonomic memory foam pillow with cooling gel layer. Provides perfect support for a good night sleep.',
        shortDescription: 'Ergonomic memory foam pillow',
        images: [
            {
                id: 'img21',
                url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
                alt: 'Memory Foam Pillow',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 599,
            currency: 'TRY',
            formatted: '₺599.00',
        },
        originalPrice: {
            amount: 899,
            currency: 'TRY',
            formatted: '₺899.00',
        },
        discount: {
            type: 'percentage',
            value: 33,
        },
        brand: mockBrands[2],
        category: mockCategories[2],
        rating: {
            average: 4.7,
            count: 423,
            distribution: {
                5: 312,
                4: 78,
                3: 28,
                2: 4,
                1: 1,
            },
        },
        stock: {
            available: 56,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Material', value: 'Memory Foam with Gel' },
            { name: 'Size', value: 'Standard (50x70cm)' },
            { name: 'Firmness', value: 'Medium' },
        ],
        tags: ['pillow', 'bedding', 'sleep'],
        createdAt: '2024-11-05T08:00:00Z',
        updatedAt: '2024-12-19T11:00:00Z',
        isFeatured: true,
        isNew: false,
    },
    {
        id: '21',
        name: 'Resistance Bands Set',
        slug: 'resistance-bands-set',
        description:
            'Complete resistance bands set with 5 different resistance levels. Perfect for full-body workouts.',
        shortDescription: 'Resistance bands set with 5 levels',
        images: [
            {
                id: 'img22',
                url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
                alt: 'Resistance Bands',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 249,
            currency: 'TRY',
            formatted: '₺249.00',
        },
        brand: mockBrands[3],
        category: mockCategories[3],
        rating: {
            average: 4.5,
            count: 198,
            distribution: {
                5: 132,
                4: 45,
                3: 18,
                2: 2,
                1: 1,
            },
        },
        stock: {
            available: 87,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Set Includes', value: '5 Bands (5-50 lbs)' },
            { name: 'Material', value: 'Natural Latex' },
            { name: 'Accessories', value: 'Door Anchor, Handles' },
        ],
        tags: ['fitness', 'resistance-bands', 'workout'],
        createdAt: '2024-11-20T09:00:00Z',
        updatedAt: '2024-12-16T12:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '22',
        name: 'Retinol Night Cream',
        slug: 'retinol-night-cream',
        description:
            'Anti-aging night cream with retinol and peptides. Reduces fine lines and improves skin texture.',
        shortDescription: 'Anti-aging retinol night cream',
        images: [
            {
                id: 'img23',
                url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800',
                alt: 'Night Cream',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 449,
            currency: 'TRY',
            formatted: '₺449.00',
        },
        brand: mockBrands[4],
        category: mockCategories[4],
        rating: {
            average: 4.6,
            count: 289,
            distribution: {
                5: 198,
                4: 62,
                3: 24,
                2: 4,
                1: 1,
            },
        },
        stock: {
            available: 41,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Volume', value: '50ml' },
            { name: 'Key Ingredients', value: 'Retinol, Peptides, Niacinamide' },
            { name: 'Skin Type', value: 'Mature Skin' },
        ],
        tags: ['skincare', 'anti-aging', 'retinol'],
        createdAt: '2024-11-12T10:00:00Z',
        updatedAt: '2024-12-17T14:00:00Z',
        isFeatured: false,
        isNew: false,
    },
    {
        id: '23',
        name: 'USB-C Hub Multiport',
        slug: 'usb-c-hub-multiport',
        description:
            '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and more. Perfect for laptops and tablets.',
        shortDescription: '7-in-1 USB-C hub',
        images: [
            {
                id: 'img24',
                url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
                alt: 'USB-C Hub',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 599,
            currency: 'TRY',
            formatted: '₺599.00',
        },
        brand: mockBrands[0],
        category: mockCategories[0],
        rating: {
            average: 4.4,
            count: 156,
            distribution: {
                5: 98,
                4: 38,
                3: 16,
                2: 3,
                1: 1,
            },
        },
        stock: {
            available: 38,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Ports', value: 'HDMI, 3x USB 3.0, SD/TF Card, USB-C PD' },
            { name: 'HDMI Output', value: '4K@30Hz' },
            { name: 'Compatibility', value: 'USB-C Devices' },
        ],
        tags: ['hub', 'usb-c', 'adapter'],
        createdAt: '2024-11-18T08:00:00Z',
        updatedAt: '2024-12-15T16:00:00Z',
        isFeatured: false,
        isNew: true,
    },
    {
        id: '24',
        name: 'Wool Winter Scarf',
        slug: 'wool-winter-scarf',
        description:
            'Warm and soft wool scarf for winter. Classic design that goes with any outfit.',
        shortDescription: 'Warm wool winter scarf',
        images: [
            {
                id: 'img25',
                url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
                alt: 'Winter Scarf',
                width: 800,
                height: 800,
            },
        ],
        price: {
            amount: 349,
            currency: 'TRY',
            formatted: '₺349.00',
        },
        brand: mockBrands[1],
        category: mockCategories[1],
        rating: {
            average: 4.3,
            count: 145,
            distribution: {
                5: 89,
                4: 38,
                3: 15,
                2: 2,
                1: 1,
            },
        },
        stock: {
            available: 62,
            status: 'in-stock',
        },
        attributes: [
            { name: 'Material', value: '100% Wool' },
            { name: 'Dimensions', value: '180 x 30 cm' },
            { name: 'Care', value: 'Dry Clean' },
        ],
        tags: ['scarf', 'winter', 'accessories'],
        createdAt: '2024-11-10T09:00:00Z',
        updatedAt: '2024-12-13T12:00:00Z',
        isFeatured: false,
        isNew: false,
    },
];